-- TruID persistence table for banking collections and captured summary payloads.
-- Run this once in Supabase SQL editor.

create table if not exists public.truid_collections (
  id bigint generated by default as identity primary key,
  collection_id text not null unique,
  user_id uuid null references public.profiles(id) on delete set null,
  application_id text null,
  consent_id text null,
  consumer_url text null,
  status text null,
  normalized_status text null,
  verified boolean not null default false,
  correlation jsonb null,
  collection_payload jsonb null,
  summary_payload jsonb null,
  capture_attempts integer not null default 0,
  captured_at timestamptz null,
  last_error text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_truid_collections_user_id on public.truid_collections(user_id);
create index if not exists idx_truid_collections_status on public.truid_collections(status);
create index if not exists idx_truid_collections_updated_at on public.truid_collections(updated_at desc);

-- Optional: if RLS is enabled on this table, allow service role full access.
-- The app writes through SUPABASE_SERVICE_ROLE_KEY on the server.
alter table public.truid_collections enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'truid_collections'
      and policyname = 'service role full access on truid_collections'
  ) then
    create policy "service role full access on truid_collections.."
      on public.truid_collections
      for all
      to service_role
      using (true)
      with check (true);
  end if;
end $$;
